#Locations
Location.create(province: 'Ho Chi Minh')
Location.create(province: 'Ha Noi')
Location.create(province: 'Quang Binh')
Location.create(province: 'Da Nang')
Location.create(province: 'Vung Tau')
Location.create(province: 'Lam Dong')
#Tags
Tag.create(name: 'Comment')
Tag.create(name: 'View')
Tag.create(name: 'Rating')
Tag.create(name: 'Ramen')
Tag.create(name: 'Photogenic')
#Categories 
Category.create(name: 'Travel')
Category.create(name: 'Work')
Category.create(name: 'Study')
Category.create(name: 'Shopping')  
Category.create(name: 'Food')
#Hosts
Host.create(email: 'mockproject@example.com', password: '123456')
#Blogs
Blog.create(location_id: 1, host_id: 1)
Blog.create(location_id: 2, host_id: 1)
Blog.create(location_id: 3, host_id: 1)
Blog.create(location_id: 4, host_id: 1)
Blog.create(location_id: 5, host_id: 1)
#Blog_details
BlogDetail.create(blog_id: 1, title: 'Blog_1', description: 'blog_test_1', content: 'It is a long established fact that a reader will be distracted by the readable content oftimes by accident, sometimes on purpose (injected humour and the like).')
BlogDetail.create(blog_id: 2, title: 'Blog_2', description: 'blog_test_2', content: 'It is a long established fact that a reader will be distracted by the readable content oftimes by accident, sometimes on purpose (injected humour and the like).')
BlogDetail.create(blog_id: 3, title: 'Blog_3', description: 'blog_test_3', content: 'It is a long established fact that a reader will be distracted by the readable content oftimes by accident, sometimes on purpose (injected humour and the like).')
BlogDetail.create(blog_id: 4, title: 'Blog_4', description: 'blog_test_4', content: 'It is a long established fact that a reader will be distracted by the readable content oftimes by accident, sometimes on purpose (injected humour and the like).')
BlogDetail.create(blog_id: 5, title: 'Blog_5', description: 'blog_test_5', content: 'It is a long established fact that a reader will be distracted by the readable content oftimes by accident, sometimes on purpose (injected humour and the like).')
# Hashtags
Hashtag.create(tag_id: 1, blog_id: 1)
Hashtag.create(tag_id: 2, blog_id: 2)
Hashtag.create(tag_id: 3, blog_id: 3)
Hashtag.create(tag_id: 4, blog_id: 4)
Hashtag.create(tag_id: 5, blog_id: 5)
#Relative_categories 
RelativeCategory.create(category_id: 1, blog_id: 1)
RelativeCategory.create(category_id: 2, blog_id: 2)
RelativeCategory.create(category_id: 3, blog_id: 3)
RelativeCategory.create(category_id: 4, blog_id: 4)
RelativeCategory.create(category_id: 5, blog_id: 5)
