Location.create(province: 'Ho Chi Minh')
Location.create(province: 'Ha Noi')
Location.create(province: 'Quang Binh')
Location.create(province: 'Da Nang')
Location.create(province: 'Vung Tau')
Location.create(province: 'Lam Dong')

Tag.create(tag_name: 'Comment')
Tag.create(tag_name: 'View')
Tag.create(tag_name: 'Rating')
Tag.create(tag_name: 'Ramen')
Tag.create(tag_name: 'Photogenic')

Category.create(category_name: 'Travel')
Category.create(category_name: 'Work')
Category.create(category_name: 'Study')
Category.create(category_name: 'Shopping')  
Category.create(category_name: 'Food')

Blog.create(location_id: 1)
Blog.create(location_id: 2)
Blog.create(location_id: 3)
Blog.create(location_id: 4)
Blog.create(location_id: 5)
Blog.create(location_id: 6)
Blog.create(location_id: 7)


Hashtag.create(blog_id: 1, tag_id: 1)
Hashtag.create(blog_id: 1, tag_id: 2)
Hashtag.create(blog_id: 2, tag_id: 1)
Hashtag.create(blog_id: 2, tag_id: 3)
Hashtag.create(blog_id: 2, tag_id: 4)
Hashtag.create(blog_id: 3, tag_id: 1)
Hashtag.create(blog_id: 4, tag_id: 1)
Hashtag.create(blog_id: 4, tag_id: 2)
Hashtag.create(blog_id: 4, tag_id: 3)

RelativeCategory.create(blog_id: 1, category_id: 1)
RelativeCategory.create(blog_id: 1, category_id: 2)
RelativeCategory.create(blog_id: 1, category_id: 3)
RelativeCategory.create(blog_id: 2, category_id: 1)
RelativeCategory.create(blog_id: 3, category_id: 2)
RelativeCategory.create(blog_id: 3, category_id: 4)
RelativeCategory.create(blog_id: 4, category_id: 1)
RelativeCategory.create(blog_id: 4, category_id: 2)
RelativeCategory.create(blog_id: 4, category_id: 3)
RelativeCategory.create(blog_id: 5, category_id: 1)

BlogDetail.create(blog_id: 1, title: 'Blog1', content: '123')
BlogDetail.create(blog_id: 2, title: 'Blog2', content: '123')
BlogDetail.create(blog_id: 3, title: 'Blog3', content: '123')
BlogDetail.create(blog_id: 4, title: 'Blog4', content: '123')
BlogDetail.create(blog_id: 5, title: 'Blog5', content: '123')
BlogDetail.create(blog_id: 6, title: 'Blog6', content: '123')
BlogDetail.create(blog_id: 7, title: 'Blog7', content: '123')
BlogDetail.create(blog_id: 8, title: 'Blog8', content: '123')
BlogDetail.create(blog_id: 9, title: 'Blog9', content: '123')
