#Locations
Location.create(province: 'Ho Chi Minh')
Location.create(province: 'Ha Noi')
Location.create(province: 'Quang Binh')
Location.create(province: 'Da Nang')
Location.create(province: 'Vung Tau')
Location.create(province: 'Lam Dong')
#Tags
Tag.create(tag_name: 'Comment')
Tag.create(tag_name: 'View')
Tag.create(tag_name: 'Rating')
Tag.create(tag_name: 'Ramen')
Tag.create(tag_name: 'Photogenic')
#Categories 
Category.create(category_name: 'Travel')
Category.create(category_name: 'Work')
Category.create(category_name: 'Study')
Category.create(category_name: 'Shopping')  
Category.create(category_name: 'Food')
#Hosts
Host.create(email: 'example1@gmail.com')
Host.create(email: 'example2@gmail.com')
Host.create(email: 'example3@gmail.com')
Host.create(email: 'example4@gmail.com')
Host.create(email: 'example5@gmail.com')
#Experiences 
Experience.create(location_id: 1)
Experience.create(location_id: 2)
Experience.create(location_id: 3)
Experience.create(location_id: 4)
Experience.create(location_id: 5)
#Blogs
Blog.create(location_id: 1, impressions_count: 30)
Blog.create(location_id: 2, impressions_count: 20)
Blog.create(location_id: 3, impressions_count: 10)
Blog.create(location_id: 4)
Blog.create(location_id: 5)
#Blog_details
BlogDetail.create(blog_id: 1, title: 'Blog_1', description: 'blog_test_1', content: 'It is a long established fact that a reader will be distracted by the readable content oftimes by accident, sometimes on purpose (injected humour and the like).')
BlogDetail.create(blog_id: 2, title: 'Blog_2', description: 'blog_test_2', content: 'It is a long established fact that a reader will be distracted by the readable content oftimes by accident, sometimes on purpose (injected humour and the like).')
BlogDetail.create(blog_id: 3, title: 'Blog_3', description: 'blog_test_3', content: 'It is a long established fact that a reader will be distracted by the readable content oftimes by accident, sometimes on purpose (injected humour and the like).')
BlogDetail.create(blog_id: 4, title: 'Blog_4', description: 'blog_test_4', content: 'It is a long established fact that a reader will be distracted by the readable content oftimes by accident, sometimes on purpose (injected humour and the like).')
BlogDetail.create(blog_id: 5, title: 'Blog_5', description: 'blog_test_5', content: 'It is a long established fact that a reader will be distracted by the readable content oftimes by accident, sometimes on purpose (injected humour and the like).')
#Hashtags
Hashtag.create(tag_id: 1, blog_id: 1)
Hashtag.create(tag_id: 2, blog_id: 2)
Hashtag.create(tag_id: 3, blog_id: 3)
Hashtag.create(tag_id: 4, blog_id: 4)
Hashtag.create(tag_id: 5, blog_id: 5)
#Relative_categories 
RelativeCategory.create(category_id: 1, blog_id: 1, experience_id: 1)
RelativeCategory.create(category_id: 2, blog_id: 2, experience_id: 2)
RelativeCategory.create(category_id: 3, blog_id: 3, experience_id: 3)
RelativeCategory.create(category_id: 4, blog_id: 4, experience_id: 4)
RelativeCategory.create(category_id: 5, blog_id: 5, experience_id: 5)
